type Props = { onBack: () => void };
const image = (name: string) => `${import.meta.env.BASE_URL}tutorial/${name}`;
function Figure({ name, alt, caption }: { name: string; alt: string; caption: string }) {
  return <figure className="tutorial-figure"><img src={image(name)} alt={alt} /><figcaption>{caption}</figcaption></figure>;
}
export default function EnglishTutorial({ onBack }: Props) {
  return <main className="tutorial-page">
    <header className="tutorial-header"><div><p className="eyebrow">HOW TO PLAY</p><h1>Yellowstone Park</h1><p className="tutorial-lead">Place animal cards skillfully, avoid penalty cards, and finish with the fewest penalty points.</p></div><button type="button" className="primary tutorial-back" onClick={onBack}>Back to game</button></header>
    <section className="tutorial-section tutorial-hero"><div><p className="eyebrow">FIRST LOOK</p><h2>The game screen</h2><p>The top row shows each player's penalty score, hand size, penalty-card count, and recent action. The board is in the center and the current player's controls are on the right.</p><p>This public version is a four-player game: you and three CPUs.</p></div><Figure name="en-game-overview.png" alt="Full English game screen" caption="The score strip, board, hand, and controls share one screen." /></section>
    <section className="tutorial-section"><p className="eyebrow">OBJECTIVE</p><h2>Setup and objective</h2><div className="tutorial-grid"><article className="tutorial-rule"><span>1</span><div><h3>Deal six cards</h3><p>Each player starts with six cards. The remaining cards form the draw pile, and the first card is placed near the center of the board.</p></div></article><article className="tutorial-rule"><span>2</span><div><h3>Play in turn</h3><p>On your turn, play one or two cards in succession onto the board.</p></div></article><article className="tutorial-rule"><span>3</span><div><h3>Avoid penalties</h3><p>Cards outside your new 3×3 frame become penalty cards. Each penalty card is one penalty point.</p></div></article></div></section>
    <section className="tutorial-section tutorial-section-split"><div><p className="eyebrow">CARD PLACEMENT</p><h2>Placing cards</h2><p>A card's number determines its row. Once a color occupies a column, only that color may be placed in the column until it becomes empty.</p><p>Legal spaces are highlighted. With automatic 3×3 frame setting ON, the frame is chosen automatically; with it OFF, you choose the frame yourself.</p></div><Figure name="en-frame-selection.png" alt="Manual 3×3 frame selection" caption="With frame setting OFF, the board shows which cards will become penalties." /></section>
    <section className="tutorial-section"><p className="eyebrow">THE 3×3 MATRIX</p><h2>The 3×3 frame and penalty cards</h2><p>A 3×3 frame is nine neighboring spaces: three rows by three columns. After a placement, collect every board card outside the chosen frame as penalty cards. When playing two cards, resolve penalties after the first placement before placing the second.</p><div className="tutorial-note"><strong>Tip</strong><span>The frame you choose determines which cards remain and which become penalties. Check the board's penalty highlight before confirming.</span></div></section>
    <section className="tutorial-section tutorial-section-split"><Figure name="action-summary.png" alt="Recent actions on the game screen" caption="Each player's recent action remains visible in the score strip." /><div><p className="eyebrow">YOUR TURN</p><h2>Playing one or two cards</h2><p>Select a card and a legal space. To finish after one card, choose “End turn with one card.” If cards remain in your hand, you cannot refill after a one-card turn.</p><p>After playing two cards, you may choose whether to refill. In this four-player version, the choices are “Draw from deck” or “Draw no cards.”</p></div></section>
    <section className="tutorial-section tutorial-section-split"><div><p className="eyebrow">REFILL</p><h2>Refilling after two cards</h2><p>After a two-card turn, if you still have cards in hand, you may draw from the deck up to six cards or draw no cards. This refill choice does not appear after a one-card turn.</p></div><Figure name="refill-options.png" alt="Refill choices after playing two cards" caption="After two cards: Draw from deck or Draw no cards." /></section>
    <section className="tutorial-section tutorial-section-split"><Figure name="empty-hand-refill.png" alt="Refill choices with an empty hand" caption="With no cards in hand: draw from the deck or from penalty cards." /><div><p className="eyebrow">NO CARDS IN HAND</p><h2>When your hand reaches zero</h2><p>If you have no cards after playing one or two cards, you must refill. Choose “Draw from deck” or “Draw from penalties.”</p><p>Drawing from penalties shuffles your penalty stack and returns up to six cards to your hand. If you have five or fewer penalty cards, you must draw six cards from the deck instead.</p></div></section>
    <section className="tutorial-section tutorial-section-split"><div><p className="eyebrow">BONUSES</p><h2>Bonuses for the 8th and 9th spaces</h2><p>Filling the 8th space of a 3×3 frame gives 1 bonus point. Filling the 9th space gives 3 bonus points. If the two cards of one turn fill the 8th and 9th spaces, the total bonus is 4 points.</p><p>Bonuses move your marker toward zero. No further bonus is awarded once it reaches zero, and placing on an already occupied space does not create a bonus.</p></div><div className="tutorial-figures"><Figure name="bonus-8th.png" alt="Board with the 8th frame space" caption="8th space: 1 bonus point." /><Figure name="bonus-9th.png" alt="Board showing the 9th-space placement example" caption="9th-space placement example: 3 bonus points." /></div></section>
    <section className="tutorial-section"><p className="eyebrow">SCORING</p><h2>Deck exhaustion and game end</h2><p>If the last card is drawn from the deck during a refill, scoring happens immediately, even if the active player could not refill to six cards.</p><p>Each player counts their penalty cards and advances their penalty marker by that amount. All penalty cards are shuffled into a new draw pile. Hands remain unchanged. The player who emptied the deck does not continue refilling; play resumes with the next player.</p><p>The game ends after a deck-exhaustion scoring when any penalty marker reaches or exceeds 35. The player closest to zero wins; tied players share the win.</p></section>
    <section className="tutorial-section tutorial-scope"><p className="eyebrow">THIS VERSION</p><h2>About this public version</h2><p>This is a four-player game against three CPUs. It uses no online play, login, server API, or account.</p></section>
    <button type="button" className="primary tutorial-bottom-back" onClick={onBack}>Back to game</button>
  </main>;
}
